
export const arrPets = [
    {
        title: "Katrine",
        img: "/shelter/images/description/description__katrine.png",
        popup: "katrine",
        type: "Сat",
        breed: "British Shorthair",
        description: "Katrine is a beautiful girl. She is as soft as the finest velvet with a thick lush fur. Will love you until the last breath she takes as long as you are the one. She is picky about her affection. She loves cuddles and to stretch into your hands for a deeper relaxations.",
        age: "6 months",
        innoculations: "panleukopenia",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Jennifer",
        img: "/shelter/images/description/description__jennifer.png",
        popup: "jennifer",
        type: "Dog",
        breed: "Labrador",
        description: "Sophia here and I'm looking for my forever home to live out the best years of my life. I am full of energy. Everyday I'm learning new things, like how to walk on a leash, go potty outside, bark and play with toys and I still need some practice. ",
        age: "1 months",
        innoculations: "parvovirus",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Woody",
        img: "/shelter/images/description/description__woody.png",
        popup: "woody",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },

    {
        title: "Sophia",
        img: "/shelter/images/description/description__sophia.png",
        popup: "sophia",
        type: "Сat",
        breed: "British Shorthair",
        description: "Katrine is a beautiful girl. She is as soft as the finest velvet with a thick lush fur. Will love you until the last breath she takes as long as you are the one. She is picky about her affection. She loves cuddles and to stretch into your hands for a deeper relaxations.",
        age: "6 months",
        innoculations: "panleukopenia",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Timmy",
        img: "/shelter/images/description/description__timmy.png",
        popup: "timmy",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },

    {
        title: "Charly",
        img: "/shelter/images/description/description__charly.png",
        popup: "charly",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },

    {
        title: "Scralett",
        img: "/shelter/images/description/description__scralett.png",
        popup: "scralett",
        type: "Сat",
        breed: "British Shorthair",
        description: "Katrine is a beautiful girl. She is as soft as the finest velvet with a thick lush fur. Will love you until the last breath she takes as long as you are the one. She is picky about her affection. She loves cuddles and to stretch into your hands for a deeper relaxations.",
        age: "6 months",
        innoculations: "panleukopenia",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Freddie",
        img: "/shelter/images/description/description__freddie.png",
        popup: "freddie",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },
    {
        title: "Katrine",
        img: "/shelter/images/description/description__katrine.png",
        popup: "katrine",
        type: "Сat",
        breed: "British Shorthair",
        description: "Katrine is a beautiful girl. She is as soft as the finest velvet with a thick lush fur. Will love you until the last breath she takes as long as you are the one. She is picky about her affection. She loves cuddles and to stretch into your hands for a deeper relaxations.",
        age: "6 months",
        innoculations: "panleukopenia",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Jennifer",
        img: "/shelter/images/description/description__jennifer.png",
        popup: "jennifer",
        type: "Dog",
        breed: "Labrador",
        description: "Sophia here and I'm looking for my forever home to live out the best years of my life. I am full of energy. Everyday I'm learning new things, like how to walk on a leash, go potty outside, bark and play with toys and I still need some practice. ",
        age: "1 months",
        innoculations: "parvovirus",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Woody",
        img: "/shelter/images/description/description__woody.png",
        popup: "woody",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },

    {
        title: "Sophia",
        img: "/shelter/images/description/description__sophia.png",
        popup: "sophia",
        type: "Сat",
        breed: "British Shorthair",
        description: "Katrine is a beautiful girl. She is as soft as the finest velvet with a thick lush fur. Will love you until the last breath she takes as long as you are the one. She is picky about her affection. She loves cuddles and to stretch into your hands for a deeper relaxations.",
        age: "6 months",
        innoculations: "panleukopenia",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Timmy",
        img: "/shelter/images/description/description__timmy.png",
        popup: "timmy",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },

    {
        title: "Charly",
        img: "/shelter/images/description/description__charly.png",
        popup: "charly",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },

    {
        title: "Scralett",
        img: "/shelter/images/description/description__scralett.png",
        popup: "scralett",
        type: "Сat",
        breed: "British Shorthair",
        description: "Katrine is a beautiful girl. She is as soft as the finest velvet with a thick lush fur. Will love you until the last breath she takes as long as you are the one. She is picky about her affection. She loves cuddles and to stretch into your hands for a deeper relaxations.",
        age: "6 months",
        innoculations: "panleukopenia",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Freddie",
        img: "/shelter/images/description/description__freddie.png",
        popup: "freddie",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },
    {
        title: "Katrine",
        img: "/shelter/images/description/description__katrine.png",
        popup: "katrine",
        type: "Сat",
        breed: "British Shorthair",
        description: "Katrine is a beautiful girl. She is as soft as the finest velvet with a thick lush fur. Will love you until the last breath she takes as long as you are the one. She is picky about her affection. She loves cuddles and to stretch into your hands for a deeper relaxations.",
        age: "6 months",
        innoculations: "panleukopenia",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Jennifer",
        img: "/shelter/images/description/description__jennifer.png",
        popup: "jennifer",
        type: "Dog",
        breed: "Labrador",
        description: "Sophia here and I'm looking for my forever home to live out the best years of my life. I am full of energy. Everyday I'm learning new things, like how to walk on a leash, go potty outside, bark and play with toys and I still need some practice. ",
        age: "1 months",
        innoculations: "parvovirus",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Woody",
        img: "/shelter/images/description/description__woody.png",
        popup: "woody",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },

    {
        title: "Sophia",
        img: "/shelter/images/description/description__sophia.png",
        popup: "sophia",
        type: "Сat",
        breed: "British Shorthair",
        description: "Katrine is a beautiful girl. She is as soft as the finest velvet with a thick lush fur. Will love you until the last breath she takes as long as you are the one. She is picky about her affection. She loves cuddles and to stretch into your hands for a deeper relaxations.",
        age: "6 months",
        innoculations: "panleukopenia",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Timmy",
        img: "/shelter/images/description/description__timmy.png",
        popup: "timmy",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },

    {
        title: "Charly",
        img: "/shelter/images/description/description__charly.png",
        popup: "charly",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },

    {
        title: "Scralett",
        img: "/shelter/images/description/description__scralett.png",
        popup: "scralett",
        type: "Сat",
        breed: "British Shorthair",
        description: "Katrine is a beautiful girl. She is as soft as the finest velvet with a thick lush fur. Will love you until the last breath she takes as long as you are the one. She is picky about her affection. She loves cuddles and to stretch into your hands for a deeper relaxations.",
        age: "6 months",
        innoculations: "panleukopenia",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Freddie",
        img: "/shelter/images/description/description__freddie.png",
        popup: "freddie",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },
    {
        title: "Katrine",
        img: "/shelter/images/description/description__katrine.png",
        popup: "katrine",
        type: "Сat",
        breed: "British Shorthair",
        description: "Katrine is a beautiful girl. She is as soft as the finest velvet with a thick lush fur. Will love you until the last breath she takes as long as you are the one. She is picky about her affection. She loves cuddles and to stretch into your hands for a deeper relaxations.",
        age: "6 months",
        innoculations: "panleukopenia",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Jennifer",
        img: "/shelter/images/description/description__jennifer.png",
        popup: "jennifer",
        type: "Dog",
        breed: "Labrador",
        description: "Sophia here and I'm looking for my forever home to live out the best years of my life. I am full of energy. Everyday I'm learning new things, like how to walk on a leash, go potty outside, bark and play with toys and I still need some practice. ",
        age: "1 months",
        innoculations: "parvovirus",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Woody",
        img: "/shelter/images/description/description__woody.png",
        popup: "woody",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },

    {
        title: "Sophia",
        img: "/shelter/images/description/description__sophia.png",
        popup: "sophia",
        type: "Сat",
        breed: "British Shorthair",
        description: "Katrine is a beautiful girl. She is as soft as the finest velvet with a thick lush fur. Will love you until the last breath she takes as long as you are the one. She is picky about her affection. She loves cuddles and to stretch into your hands for a deeper relaxations.",
        age: "6 months",
        innoculations: "panleukopenia",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Timmy",
        img: "/shelter/images/description/description__timmy.png",
        popup: "timmy",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },

    {
        title: "Charly",
        img: "/shelter/images/description/description__charly.png",
        popup: "charly",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },

    {
        title: "Scralett",
        img: "/shelter/images/description/description__scralett.png",
        popup: "scralett",
        type: "Сat",
        breed: "British Shorthair",
        description: "Katrine is a beautiful girl. She is as soft as the finest velvet with a thick lush fur. Will love you until the last breath she takes as long as you are the one. She is picky about her affection. She loves cuddles and to stretch into your hands for a deeper relaxations.",
        age: "6 months",
        innoculations: "panleukopenia",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Freddie",
        img: "/shelter/images/description/description__freddie.png",
        popup: "freddie",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },
    {
        title: "Katrine",
        img: "/shelter/images/description/description__katrine.png",
        popup: "katrine",
        type: "Сat",
        breed: "British Shorthair",
        description: "Katrine is a beautiful girl. She is as soft as the finest velvet with a thick lush fur. Will love you until the last breath she takes as long as you are the one. She is picky about her affection. She loves cuddles and to stretch into your hands for a deeper relaxations.",
        age: "6 months",
        innoculations: "panleukopenia",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Jennifer",
        img: "/shelter/images/description/description__jennifer.png",
        popup: "jennifer",
        type: "Dog",
        breed: "Labrador",
        description: "Sophia here and I'm looking for my forever home to live out the best years of my life. I am full of energy. Everyday I'm learning new things, like how to walk on a leash, go potty outside, bark and play with toys and I still need some practice. ",
        age: "1 months",
        innoculations: "parvovirus",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Woody",
        img: "/shelter/images/description/description__woody.png",
        popup: "woody",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },

    {
        title: "Sophia",
        img: "/shelter/images/description/description__sophia.png",
        popup: "sophia",
        type: "Сat",
        breed: "British Shorthair",
        description: "Katrine is a beautiful girl. She is as soft as the finest velvet with a thick lush fur. Will love you until the last breath she takes as long as you are the one. She is picky about her affection. She loves cuddles and to stretch into your hands for a deeper relaxations.",
        age: "6 months",
        innoculations: "panleukopenia",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Timmy",
        img: "/shelter/images/description/description__timmy.png",
        popup: "timmy",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },

    {
        title: "Charly",
        img: "/shelter/images/description/description__charly.png",
        popup: "charly",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },

    {
        title: "Scralett",
        img: "/shelter/images/description/description__scralett.png",
        popup: "scralett",
        type: "Сat",
        breed: "British Shorthair",
        description: "Katrine is a beautiful girl. She is as soft as the finest velvet with a thick lush fur. Will love you until the last breath she takes as long as you are the one. She is picky about her affection. She loves cuddles and to stretch into your hands for a deeper relaxations.",
        age: "6 months",
        innoculations: "panleukopenia",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Freddie",
        img: "/shelter/images/description/description__freddie.png",
        popup: "freddie",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },
    {
        title: "Katrine",
        img: "/shelter/images/description/description__katrine.png",
        popup: "katrine",
        type: "Сat",
        breed: "British Shorthair",
        description: "Katrine is a beautiful girl. She is as soft as the finest velvet with a thick lush fur. Will love you until the last breath she takes as long as you are the one. She is picky about her affection. She loves cuddles and to stretch into your hands for a deeper relaxations.",
        age: "6 months",
        innoculations: "panleukopenia",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Jennifer",
        img: "/shelter/images/description/description__jennifer.png",
        popup: "jennifer",
        type: "Dog",
        breed: "Labrador",
        description: "Sophia here and I'm looking for my forever home to live out the best years of my life. I am full of energy. Everyday I'm learning new things, like how to walk on a leash, go potty outside, bark and play with toys and I still need some practice. ",
        age: "1 months",
        innoculations: "parvovirus",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Woody",
        img: "/shelter/images/description/description__woody.png",
        popup: "woody",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },

    {
        title: "Sophia",
        img: "/shelter/images/description/description__sophia.png",
        popup: "sophia",
        type: "Сat",
        breed: "British Shorthair",
        description: "Katrine is a beautiful girl. She is as soft as the finest velvet with a thick lush fur. Will love you until the last breath she takes as long as you are the one. She is picky about her affection. She loves cuddles and to stretch into your hands for a deeper relaxations.",
        age: "6 months",
        innoculations: "panleukopenia",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Timmy",
        img: "/shelter/images/description/description__timmy.png",
        popup: "timmy",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },

    {
        title: "Charly",
        img: "/shelter/images/description/description__charly.png",
        popup: "charly",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },

    {
        title: "Scralett",
        img: "/shelter/images/description/description__scralett.png",
        popup: "scralett",
        type: "Сat",
        breed: "British Shorthair",
        description: "Katrine is a beautiful girl. She is as soft as the finest velvet with a thick lush fur. Will love you until the last breath she takes as long as you are the one. She is picky about her affection. She loves cuddles and to stretch into your hands for a deeper relaxations.",
        age: "6 months",
        innoculations: "panleukopenia",
        diseases: "none",
        parasites: "none",
    },

    {
        title: "Freddie",
        img: "/shelter/images/description/description__freddie.png",
        popup: "freddie",
        type: "Dog",
        breed: "Golden Retriever",
        description: "Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.",
        age: "3 years 6 months",
        innoculations: "adenovirus, distemper",
        diseases: "right back leg mobility reduced",
        parasites: "none",
    },
];

export const arrcards = [
    {
        title: "Katrine",
        img: "/shelter/images/description/description__katrine.png",
    },

    {
        title: "Jennifer",
        img: "/shelter/images/description/description__jennifer.png",
    },

    {
        title: "Woody",
        img: "/shelter/images/description/description__woody.png",
    },

    {
        title: "Sophia",
        img: "/shelter/images/description/description__sophia.png",
    },

    {
        title: "Timmy",
        img: "/shelter/images/description/description__timmy.png",
    },

    {
        title: "Charly",
        img: "/shelter/images/description/description__charly.png",
    },

    {
        title: "Scralett",
        img: "/shelter/images/description/description__scralett.png",
    },

    {
        title: "Freddie",
        img: "/shelter/images/description/description__freddie.png",
    },


];
